---
title: 'Practical Machine Learning: Assignment 1'
author: "Vivek Verma"
date: "27 March 2016"
output: pdf_document
---

# Machine Learning: An Analysis of the Weight Lifting Exercises Dataset


##Executive Summary
This project, the goal is to analyze data from accelerometers on the belt, forearm, arm, and dumbell of six participants. They were asked to perform barbell lifts correctly and incorrectly in five different ways.
Specifically, the goal of this machine learning exercise is to predict the manner in which the participants did the exercise-that is, to predict the "classe" variable found in the training set. The prediction model will then be used to predict twenty different test cases, as provided in the testing dataset.

###Data Processing and Analysis
We begin by loading the required libraries and reading in the training and testing datasets, assigning missing values to entries that are currently 'NA' or blank.

```{r0}
library(randomForest)
library(corrplot)
library(caret)

```
```{r1}
wm <- read.csv("pml-training.csv", header = TRUE, na.strings = c("NA","" ,"#DIV/0!"))
wm_test <- read.csv("pml-testing.csv", header = TRUE, na.strings = c("NA","" ,"#DIV/0!"))
```
Columns in the orignal training and testing datasets that are mostly filled with missing values are then removed. To do this, count the number of missing values in each column of the full training dataset. We use those sums to create a logical variable for each column of the dataset. The logical variable's value is 'TRUE' if a column has no missing values (i.e. if the colSums = 0). If there are missing values in the column, the logical variable's value corresponding to that column will be 'FALSE'.

Applying the logical variable to the columns of the training and testing datasets will only keep those columns that are complete.

Training dataset has fewer variables to review. Further, final testing dataset has consistent columns in it when compared with those in our slimmed-down training dataset. This will allow the fitted model (based on our training data) to be applied to the testing dataset.

```{r2}
csums <- colSums(is.na(wm))
csums_log <- (csums == 0)
training_fewer_cols <- wm[, (colSums(is.na(wm)) == 0)]
wm_test <- wm_test[, (colSums(is.na(wm)) == 0)]
```
Lnother logical vector in order to delete additional unnecessary columns from the training and testing datasets. Column names in the dataset containing the entries shown in the 'grepl' function will have a value of 'TRUE' in the logical vector. Since these are the columns we want to remove, we apply the negation of the logical vector against the columns of our dataset.

```{r3}
del_cols_log <- grepl("X|user_name|timestamp|new_window", colnames(training_fewer_cols))
training_fewer_cols <- training_fewer_cols[, !del_cols_log]
wm_test_final <- wm_test[, !del_cols_log]
```

Updated training dataset into a training dataset (70% of the observations) and a validation dataset (30% of the observations). This validation dataset will allow us to perform cross validation when developing model.

```{r4}
inTrain = createDataPartition(y = training_fewer_cols$classe, p = 0.7, list = FALSE)
small_train = training_fewer_cols[inTrain, ]
small_valid = training_fewer_cols[-inTrain, ]
```
Dataset contains 54 variables, with the last column containing the 'classe' variable we are trying to predict. Begin by looking at the correlations between the variables in our dataset. WWant to remove highly correlated predictors from our analysis and replace them with weighted combinations of predictors. This may allow a more complete capture of the information available.

```{r5}
corMat <- cor(small_train[,-54])
corrplot(corMat, order = "FPC", method = "color", type = "lower", tl.cex = 0.8, tl.col = rgb(0,0,0))
```
This plot shows the correlation between pairs of the predictors in our dataset. From a high-level perspective darker blue and darker red squares indicate high positive and high negative correlations, respectively. Based on this observation, we choose to implement a principal components analysis to produce a set of linearly uncorrelated variables to use as our predictors.

###Analysis and Machine Learning
The 'predict' function to apply the pre-processing to both the training and validation subsets of the original larger 'training' dataset.

```{r6}
preProc <- preProcess(small_train[, -54], method = "pca", thresh = 0.99)
trainPC <- predict(preProc, small_train[, -54])
valid_testPC <- predict(preProc, small_valid[, -54])
```
A model using a random forest approach on the smaller training dataset. We chose to specify the use of a cross validation method when applying the random forest routine parameter. Without specifying this, the default method (bootstrapping) would have been used. The bootstrapping method
seemed to take a lot longer to complete, while essentially producing the same level of 'accuracy'.

```{r7}
modelFit <- train(small_train$classe ~ ., method = "rf", data = trainPC, trControl = trainControl(method = "cv", 
    number = 4), importance = TRUE)
```

Now review the relative importance of the resulting principal components of the trained model, 'modelFit'.

```{r8}
varImpPlot(modelFit$finalModel, sort = TRUE, type = 1, pch = 19, col = 1, cex = 1, 
    main = "Importance of the Individual Principal Components")
```

###Cross Validation Testing and Out-of-Sample Error Estimate
Call the 'predict' function again so that our trained model can be applied to our cross validation test dataset. We can then view the resulting table in the 'confusionMatrix' function's output to see how well the model predicted/classified the values in the validation test set (i.e. the 'reference' values)

```{r9}
pred_valid_rf <- predict(modelFit, valid_testPC)
confus <- confusionMatrix(small_valid$classe, pred_valid_rf)
confus$table
```

The estimated out-of-sample error is 1.000 minus the model's accuracy, the later of which is provided in the output of the confusionmatrix, or more directly via the 'postresample' function.

```{r10}
accur <- postResample(small_valid$classe, pred_valid_rf)
model_accuracy <- accur[[1]]
model_accuracy
```

```{r11}
out_of_sample_error <- 1 - model_accuracy
out_of_sample_error
```
The estimated accuracy of the model is 98.4% and the estimated out-of-sample error based on our fitted model applied to the cross validation dataset is 1.6%.

###Predicted Results
Finally, we apply the pre-processing to the original testing dataset, after removing the extraneous column labeled 'problem_id' (column 54). We then run our model against the testing dataset and display the predicted results.

```{r12}
testPC <- predict(preProc, wm_test_final[, -54])
pred_final <- predict(modelFit, testPC)
pred_final
```
